#
# Copyright (c) 2006-2019 Wade Alcorn - wade@bindshell.net
# Browser Exploitation Framework (BeEF) - http://beefproject.com
# See the file 'doc/COPYING' for copying permission
#
beef:
    module:
        get_stored_credentials:
            enable: true
            category: ["Browser", "Hooked Origin"]
            name: "Get Stored Credentials"
            description: "This module retrieves saved username/password combinations from the login page on the Hooked Origin.<br /><br />It will fail if more than one set of domain credentials are saved in the browser."
            authors: ["bcoles"]
            target:
                working: ["FF"]
                not_working: ["All"]

